### ISSUE TITLE
[HTML]: Pagina 'accesso-negato.html' 

### ISSUE THREAD

**Issue by EduBic** [o5k1/TecWeb-progetto#2]
La pagina acceso-negato.html in /public-html serve in tutti i casi qualcuno provi ad accedere all'area riservata tramite link diretti dove non si può e sessioni non inizializzate attreverso il login.

C'è bisogno di sistemargli al struttura html per renderla omogenea con le altre (attualmente non ha nemmeno il link al css).

**Comment by o5k1** [comment]
Apposto?

**Comment by EduBic** [comment]
Ottimo!
