### ISSUE TITLE
[HTML]: Form login

### ISSUE THREAD

**Issue by EduBic** [o5k1/TecWeb-progetto#3]
Per accedere all'area riservata ho la necessità di una form costruita così:

```
<form action="../cgi-bin/check-login.cgi" method="post">
                  <fieldset>
                     <legend>Inserisci i dati per accedere all'area riservata</legend>
                     <label>Nome Utente</label><input type="text" name="username" />
                     <label>Password</label><input type="password" name="password" />
                        <input type="submit" name="accedi" value="Accedi" />
                  </fieldset>
  </form>
```

Attualmente la pagina nel repo login.html svolge questo compito ma non è indirizzata dalle altre pagine e deve essere messa a posto strutturalmente.
Lascio a te Andrea la scelta se fare una form nel footer in ogni pagina oppure tenere login.html ristrutturarla e linkarla dalle altre pagi

**Comment by davidecastello** [comment]
Io propongo di mettere la form nel footer di ogni pagina e nel caso in cui si sbaglino le credenziali di accesso (o si provi ad accedere direttamente dall'URL ad una pagina privata) si viene reindirizzati a login.html con un messaggio di errore

**Comment by o5k1** [comment]
Io pensavo invece di mettere solo un link "Area amministratore" nel footer che rimandi alla pagina di login. Così, nella versione mobile, lo rendo facilmente inaccessibile nascondendo il link con display:none. Inoltre, creando una pagina dedicata,  il form permette un inserimento più agevole. Altra cosa: non mi piace che un utente medio che visita la pagina possa trovare facilmente il login, voglio complicargli la vita aggiungendo almeno un hop in più 😁

**Comment by EduBic** [comment]
Visto che l'area riservata è esclusiva dell'amministratore che noi riteniamo 'essere uno che se ne intende' nascondere la form mi sembra un'ottima soluzione. 
Alla fine il visitatore ci guadagna perchè a lui non deve fregargli niente.

Andrea appena puoi fai come hai detto.

**Comment by o5k1** [comment]
La pagina login sarà pronta stasera, perché oggi lavoro

**Comment by o5k1** [comment]
se siete soddisfatti del lavoro fatto, chiudete l'issue

**Comment by o5k1** [comment]
@EduBic ho modificato la form aggiungendo un div e l'id dell'input "submit" per questioni di css, ti chiedo di modificare di conseguenza il cgi (trovi il codice nel file login.html) .
Ho inoltre aggiunto, tra i meta di tutte le pagine, il tag:

`<link rel="shortcut icon" type="image/png" href="images/favicon.png"/>`

per aggiungere la favicon da browser:

![cattura](https://cloud.githubusercontent.com/assets/15019796/12699107/10eb7818-c7b0-11e5-85a7-b348030a61f6.PNG)

**Comment by o5k1** [comment]
@EduBic:
- [x] Sostituire _Area riservata_ con _Area amministratore_;
- [x] A mio avviso non ha senso che compaia **Area riservata - Esci** ancora prima di fare il login, la schermata di login non è area riservata;
- [x] **Area riservata - Esci** compare anche accedendo alla sezione 'Menu', modificare in modo che appaia solo se si accede al menù per la modifica;
  ![cattura](https://cloud.githubusercontent.com/assets/15019796/12702176/ac8219c4-c820-11e5-9911-6190626d6c35.PNG)
