### ISSUE TITLE
[CGI, CSS]: cambiare id="add-piatto" in class

### ISSUE THREAD

**Issue by davidecastello** [o5k1/TecWeb-progetto#32]
@o5k1

**Comment by EduBic** [comment]
Ho fatto ma non so se ho generato problemi in giro. MI sembra di no.

**Comment by davidecastello** [comment]
@o5k1 dai un'occhiata anche tu quando riesci se questa modifica ha generale problemi. Torno a morire sulla relazione, ciao :wave:
