### ISSUE TITLE
[XMLSchema]: Schema file menu.xml

### ISSUE THREAD

**Issue by EduBic** [o5k1/TecWeb-progetto#4]
Bisogna sistemarlo. 
Tenete conto che in ogni elemento è possibile inserire tag validi.
Non credo ci sia molta differenza tra cibo - bevande e tra portate - listaBevande. 

Davide puoi farlo tu? Così ti alleni anche per l'esame. ;)
- [x] vino con bevanda
- [x] birra con bevanda
- [x] listaVini e listabirre e listaAltreBevande con listaBevande
- [x] i menu fissi sono spariti. 
- [ ] tieni conto che in ogni tag nome e descrizione (sia di piatto che di bevanda) possono contenere tag html (guarda gli esempi della Gaggi)

**Comment by davidecastello** [comment]
Non ho capito il problema, spiegati meglio :)

**Comment by EduBic** [comment]
Tag rinominati: 
- vino con bevanda
- birra con bevanda
- listaVini e listabirre e listaAltreBevande con listaBevande
  listaBevande ha un id che corrisponde al text all'interno di nome in Camelcase, praticamente si comporta come il Tag portata.
  il tag bevanda si differenzia da piatto per i Tag contenuti (piatto ha il tag numero in più).
- i menu fissi sono spariti. 
- tieni conto che in ogni tag nome e descrizione (sia di piatto che di bevanda) possono contenere tag html (guarda gli esempi della Gaggi)

Tutti gli id andrebbero uniformati al CamelCase (tolti gli spazi e maiuscole) ma questo lo farò io più avanti. 

Guarda il file menu.xml per chiarirti

**Comment by davidecastello** [comment]
Ho visto l'esempio della Gaggi però in quel caso aveva una descrizione di un film, che poteva contenere `<span>` (per le parole in inglese), `<p>` (perché la descrizione poteva essere lunga) o `<a>` (per i link al sito magari).
Ma nei nostri tag `<nome` e `<descrizione>` non vedo la possibilità di nessuna di queste 3 cose, sinceramente. Forse solo `<span>` per le parole straniere. @EduBic, @o5k1, se dite lo aggiungo :+1:

**Comment by EduBic** [comment]
Esatto span deve essere inserito per le parole straniere. 

Infatti tutto il doc xml è da aggiornare con questi accorgimenti (gulp).
