### ISSUE TITLE
[JS]: Nasconde nomi sezioni allo SR

### ISSUE THREAD

**Issue by davidecastello** [o5k1/TecWeb-progetto#5]
Sulla versione mobile del sito, Javascript nasconde oltre alle varie sezioni del sito anche i nomi delle sezioni allo screen reader.

**Comment by EduBic** [comment]
Intendi che nasconde il nav? È strano, alla fine sono tag nascosti con CSS.

**Comment by davidecastello** [comment]
Allora credo che sia la "Vista Reader" dell'iPhone che non è un vero e proprio screen reader :sweat_smile: 
Proveremo nei prossimi giorni con lo SR e controlleremo che sia tutto ok, per il momento lascio aperta l'issue :+1:

**Comment by EduBic** [comment]
@o5k1 metti nella classe CSS hidden `display: hidden;`

**Comment by o5k1** [comment]
Non esiste `display: hidden`. Esiste `visibility: hidden` che, però, serve a poco in quanto nasconde l'elemento ma occupa ugualmente spazio:
![cattura](https://cloud.githubusercontent.com/assets/15019796/12796443/06a97c30-cabf-11e5-9028-ab07ffe2dbbc.PNG)

La soluzione migliore che ho trovato segue lo stesso principio dell'_image replacement_: invece di nascondere il contenuto del nav, lo spara fuori dallo schermo, ma dovrebbe comunque essere letto da screen reader.
Resta da provare per conferma.

**Comment by EduBic** [comment]
Ho trovato questo http://webaim.org/techniques/css/invisiblecontent/

**Comment by o5k1** [comment]
Nel link suggeriscono la metodologia simil-image replacement che ho indicato nel mio messaggio precedente, ho usato quella ma è comunque da testare.
