### ISSUE TITLE
[HTML]: Sezione Curiosità va a capo su Safari

### ISSUE THREAD

**Issue by davidecastello** [o5k1/TecWeb-progetto#7]
Allego lo screenshot.
<img width="1280" alt="schermata 2016-01-29 alle 17 38 29" src="https://cloud.githubusercontent.com/assets/14249532/12681732/55de55d6-c6b0-11e5-9a33-57df0b50f36e.png">

**Comment by EduBic** [comment]
Anche su Firefox ho lo stesso effetto.

Consiglio di rudurre di poco la dimensione dei caratteri oppure ridurre lo spazio tra le <li>.
